### ISSUE TITLE
This code is an embarrassment and needs DRYing out

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/trumps.spacing-responsive#1]
Way too much repetition in here. I don’t want to create some funky generate-everything-in-one-go kinda Sass, but I would like to try and wrap this up into a mixin. Unfortunately, progress so far hasn’t been great: http://sassmeister.com/gist/dfb20bc343bcd09e7011

**Comment by nenadjelovac** [comment]
@csswizardry [this](https://gist.github.com/nenadjelovac/8d33b86e12c565c20c18) (quick)fixes it. Lines 98 and 106. That is currently the only way to access mixin variable from global scope in SASS. I think I remember there's an open issue in SASS repo, but I don't have the time to look into it now. BTW, there could be improvements to your mixins via SASS maps (do I sound like Hugo? :)), but as I said I don't have the time to offer suggestions now.

**Comment by nenadjelovac** [comment]
Ok, I couldn't help it and had to do [maps version](https://gist.github.com/nenadjelovac/f1e564e191bc92c2111f) :) But while doing it I realized you might want to support older versions of sass and that's why you did it with maps. However, I suggest supporting SASS 3.3+ for inuit, but that's a whole other topic on its own.

**Comment by KittyGiraudel** [comment]
It turns out to be really easy to do as I first suspected. You need 3 configuration variables:
1. `$inuit-spacing`, the default spacing used for all helpers
2. `$breakpoints`, your breakpoints map
3. `$helpers`, a fresh new map of helpers where keys are aliases and values properties

``` scss
/**
 * Default inuit spacing
 * @type Number
 */
$inuit-spacing: 10px !default;

/**
 * Breakpoints map
 * @type Map
 */
$breakpoints: (
  "palm":          "screen and (max-width: 719px)",
  "lap":           "screen and (min-width: 720px) and (max-width: 1023px)",
  "lap-and-up":    "screen and (min-width: 720px)",
  "portable":      "screen and (max-width: 1023px)",
  "desk":          "screen and (min-width: 1024px)"
) !default;

/**
 * Helpers map
 * @access private
 * @type Map
 */
$helpers: (
  "m": "margin",
  "mt": "margin-top",
  "mr": "margin-right",
  "mb": "margin-bottom",
  "ml": "margin-left",
  "mh": "margin-right" "margin-left",
  "mv": "margin-top" "margin-bottom",

  "p": "padding",
  "pt": "padding-top",
  "pr": "padding-right",
  "pb": "padding-bottom",
  "pl": "padding-left",
  "ph": "padding-right" "padding-left",
  "pv": "padding-top" "padding-bottom"
) !default;
```

Then, our `inuit-generate-responsive-variants`. This mixin does one thing and one thing only: it loops over the breakpoints and include a `inuit-generate-responsive-variant` (no `s` this time) passing it the breakpoint name (or alias, as you wish).

``` scss
/**
 * Generate responsive variants for all breakpoints
 * @requires $breakpoints
 * @requires {mixin} inuit-generate-responsive-variant
 */
@mixin inuit-generate-responsive-variants {
  @each $breakpoint-name, $breakpoint-value in $breakpoints {
    @include inuit-generate-responsive-variant($breakpoint-name);
  }
}
```

Last but not least, our `inuit-generate-responsive-variant` mixin. This is where most of the logic happens. Basically, we output the media query mapped to the given breakpoint name at root level. Then we loop over the helpers to build classes named after both the breakpoint name and the helper alias. And finally, we output the property with `$inuit-spacing` as value. Little condition has to be done here for `mv`/`mh`/`pv`/`ph` because they generate several properties instead of a single one.

``` scss
/**
 * Generate responsive variants for given breakpoint
 * @param {String} $breakpoint-name
 * @requires $helpers
 * @requires $inuit-spacing
 */
@mixin inuit-generate-responsive-variant($breakpoint-name) {
  $breakpoint-value: map-get($breakpoints, $breakpoint-name);

  // Output a new media query at root level
  @at-root {
    @media #{$breakpoint-value} {

      // Loop over the helpers in $helpers
      @each $alias, $property in $helpers {

        // Create a new class
        .#{$breakpoint-name}-#{$alias} {

          // If helper contains several properties, loop over them 
          @if length($property) > 1 {
            @each $prop in $property {
              #{$prop}: $inuit-spacing !important;
            }
          }

          // If helper is a single property, output it
          @else {
            #{$property}: $inuit-spacing !important;
          }
        }
      }
    }
  }
}
```

And now we run the whole thing with a single line.

``` scss
@include inuit-generate-responsive-variants;
```

If you need anything else, be sure to ask. By the way, you can play with the code here: http://sassmeister.com/gist/2675a636695ab23b403e.
