### ISSUE TITLE
How is mobile first supposed to work with this?

### ISSUE THREAD

**Issue by jochenstu** [inuitcss/trumps.spacing-responsive#8]
Simple use case:

.wrapper {
    max-width: $page-max-width;
    @extend .p--;
    @extend .lap-and-up-p-;
    @extend .desk-p;
    margin: 0 auto;
}

This doesn't work, because .lap-and-up-p- will trump .desk-p by source order.

The obvious way to fix this, that I can see, would require for the source to be sorted by (ascending) breakpoints instead of p-types and thus a major rewrite of the whole module.

Am I missing something here? Am I missusing the component? Any help would be appreciated.

**Comment by nenadjelovac** [comment]
Those classes were never meant to be extended. You should use them only in your markup (html) to build your component. Something like this:

``` html
<div class="wrapper  p--  lap-and-up-p-  desk-p">
  ...
</div>
```

But since your `.wrapper` class would probably be used more than once it's better to replicate what you need with [inuit breakpoint mixin](https://github.com/inuitcss/tools.responsive/blob/master/_tools.responsive.scss#L32) and [inuit spacing variables](https://github.com/inuitcss/settings.defaults/blob/master/_settings.defaults.scss#L40-L44). Maybe:

``` scss
.wrapper {
    max-width: $page-max-width;
    padding: $inuit-base-spacing-unit--tiny;
    margin: 0 auto;

    @include media-query(desk) {
        padding: $inuit-base-spacing-unit;
    }

    @include media-query(lap-and-up) {
        padding: $inuit-base-spacing-unit--small;
    }
}
```

> This doesn't work, because .lap-and-up-p- will trump .desk-p by source order.

Also, from technical side this wouldn't work because you can't extend (at the moment) from and out of `@media` scope in SASS. You'd get something like this:

```
You may not @extend an outer selector from within @media. 
You may only @extend selectors within the same directive.
```

Check [this article about SASS extend](http://www.sitepoint.com/sass-extend-nobody-told-you/) for more info.
